[build]
builder = "RAILPACK"

[env]
RAILWAY_BUILDER = "RAILPACK"
RAILPACK_PRUNE_DEPS = "false"
ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NPM_CONFIG_OPTIONAL = "false"
SKIP_NATIVE_MODULES = "1"
VSCODE_SKIP_NODE_VERSION_CHECK = "1"
NODE_ENV = "production"