[build]
buildCommand = "bash scripts/railway-build.sh"
nixpacksVersion = "1.29.1"
nixpacksPlan = {
  phases = {
    install = {
      cmds = [
        "npm config set registry https://registry.npmjs.org/",
        "npm config set fetch-timeout 120000",
        "npm config set fetch-retries 5",
        "npm config set legacy-peer-deps true",
        "npm install --omit=dev --omit=optional --legacy-peer-deps --no-audit --no-fund"
      ]
    }
  }
}
watchPatterns = [
  "/scripts/railway-vscode-server.mjs",
  "/package.json",
  "/.npmrc"
]

[deploy]
startCommand = "npm start"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
SKIP_NATIVE_MODULES = "1"
ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NPM_CONFIG_OPTIONAL = "false"
RAILPACK_PRUNE_DEPS = "false"
npm_config_target_platform = "linux"
npm_config_arch = "x64"
npm_config_disturl = "https://nodejs.org/dist"
npm_config_runtime = "node"
npm_config_build_from_source = "false"
