[build]
buildCommand = "yarn build"
nixpacksVersion = "1.29.1"
watchPatterns = [
  "/scripts/railway-vscode-server.mjs",
  "/package.json",
  "/yarn.lock"
]

[deploy]
startCommand = "yarn start"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
SKIP_NATIVE_MODULES = "1"
ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NPM_CONFIG_OPTIONAL = "false"
RAILPACK_PRUNE_DEPS = "false"
