[build]
builder = "dockerfile"
buildCommand = "npm run railway:build"
watchPatterns = [
  "/scripts/railway-server-production.mjs",
  "/package.json",
  "/Dockerfile"
]

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
SKIP_NATIVE_MODULES = "1"
ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NPM_CONFIG_OPTIONAL = "false"
